apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-20gb
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  hostPath:
    path: /var/mnt/hostpath-provisioner/nginx-20gb
