---
apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: alma-2core
spec:
  replicas: 1
  selector:
    matchLabels:
      kubevirt.io/vmpool: alma-2core
  virtualMachineTemplate:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vmpool: alma-2core
    spec:
      running: true
      template:
        metadata:
          creationTimestamp: null
          labels:
            kubevirt.io/vmpool: alma-2core
        spec:
          architecture: amd64
          domain:
            cpu:
              cores: 2
              sockets: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  bootOrder: 1
                  name: containerdisk
                - disk:
                    bus: virtio
                  bootOrder: 2
                  name: pvc
                - disk:
                    bus: virtio
                  name: cloudinit
              interfaces:
                - name: eth0
                  bridge: {}
            resources:
              requests:
                memory: 4Gi
          networks:
            - name: eth0
              multus:
                networkName: br0
          terminationGracePeriodSeconds: 0
          accessCredentials:
            - sshPublicKey:
                source:
                  secret:
                    secretName: user-kc2-sshpubkey
                propagationMethod:
                  qemuGuestAgent:
                    users:
                      - "alma"
          volumes:
            - dataVolume:
              containerDisk:
                image: docker.io/containercraft/almalinux:8
              name: containerdisk
            - dataVolume:
                name: pvc
              name: pvc
            - name: cloudinit
              cloudInitNoCloud:
                networkData: |
                  version: 2
                  ethernets:
                    enp1s0:
                      dhcp4: true
                      dhcp6: false
                      dhcp-identifier: mac
                userData: |
                  #cloud-config
                  ssh_pwauth: true
                  disable_root: true
                  chpasswd:
                    list: |
                      alma:alma
                    expire: False
                  users:
                    - name: alma
                      shell: /bin/bash
                      lock_passwd: false
                      sudo: ['ALL=(ALL) NOPASSWD:ALL']
                      groups: sudo,kvm,lxd,libvirt,microk8s,xrdp,docker,ssl-cert
                  growpart:
                    mode: auto
                    devices: ['/']
                    ignore_growroot_disabled: true
                  package_update: true
                  package_upgrade: true
                  package_reboot_if_required: true
                  packages:
                    - vim
                    - neofetch
                    - curl
                    - gpg
                    - ca-certificates
      dataVolumeTemplates:
        - metadata:
            name: pvc
          spec:
            storage:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
            source:
              http:
                url: "https://factory.talos.dev/image/79c3d43dd90861d1ffdd379da3e5a6e7fccdb36be434d4b3749ecae8882b08a9/v1.7.6/nocloud-amd64.iso"
