---
apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: omni
spec:
  replicas: 1
  selector:
    matchLabels:
      kubevirt.io/vmpool: omni
  virtualMachineTemplate:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vmpool: omni
    spec:
      running: true
      template:
        metadata:
          creationTimestamp: null
          labels:
            kubevirt.io/vmpool: omni
        spec:
          architecture: amd64
          domain:
            cpu:
              cores: 2
              sockets: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  bootOrder: 1
                  name: containerdisk
                - disk:
                    bus: virtio
                  name: cloudinit
              interfaces:
                - name: eth0
                  bridge: {}
            resources:
              requests:
                memory: 4Gi
          networks:
            - name: eth0
              multus:
                networkName: br0
          terminationGracePeriodSeconds: 0
          volumes:
            - dataVolume:
              containerDisk:
                image: docker.io/containercraft/ubuntu:22.04
              name: containerdisk
            - name: cloudinit
              cloudInitNoCloud:
                secretRef:
                  name: omni-cloud-init
