apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-registry-cache
  namespace: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quay-registry-cache
  template:
    metadata:
      labels:
        app: quay-registry-cache
    spec:
      containers:
        - name: registry
          image: registry:2
          env:
            - name: REGISTRY_PROXY_REMOTEURL
              value: https://quay.io
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: quay-registry-cache-service
  namespace: cache
spec:
  type: NodePort
  selector:
    app: quay-registry-cache
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30004 # This is the external port that will be exposed on the node.

