apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-registry-cache
  namespace: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-registry-cache
  template:
    metadata:
      labels:
        app: k8s-registry-cache
    spec:
      containers:
        - name: registry
          image: registry:2
          env:
            - name: REGISTRY_PROXY_REMOTEURL
              value: https://registry.k8s.io
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-registry-cache-service
  namespace: cache
spec:
  type: NodePort
  selector:
    app: k8s-registry-cache
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002
