apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-cache
  namespace: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-cache
  template:
    metadata:
      labels:
        app: docker-registry-cache
    spec:
      containers:
        - name: registry
          image: registry:2
          env:
            - name: REGISTRY_PROXY_REMOTEURL
              value: https://registry-1.docker.io
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-cache-service
  namespace: cache
spec:
  type: NodePort
  selector:
    app: docker-registry-cache
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000 # This is the external port that will be exposed on the node.

